In [5]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/accidents-in-france-from-2005-to-2016/vehicles.csv
/kaggle/input/accidents-in-france-from-2005-to-2016/holidays.csv
/kaggle/input/accidents-in-france-from-2005-to-2016/users.csv
/kaggle/input/accidents-in-france-from-2005-to-2016/places.csv
/kaggle/input/accidents-in-france-from-2005-to-2016/caracteristics.csv

In [6]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

import numpy as np
import scipy.stats as ss

In [7]:
charac_df = pd.read_csv('../input/accidents-in-france-from-2005-to-2016/caracteristics.csv', encoding = 'ISO-8859-1')
holidays_df = pd.read_csv('../input/accidents-in-france-from-2005-to-2016/holidays.csv')
places_df = pd.read_csv('../input/accidents-in-france-from-2005-to-2016/places.csv')
users_df = pd.read_csv('../input/accidents-in-france-from-2005-to-2016/users.csv')
vehicles_df = pd.read_csv('../input/accidents-in-france-from-2005-to-2016/vehicles.csv')

In [8]:
#total columns
charac_df.shape[1] + holidays_df.shape[1]  + places_df.shape[1] + users_df.shape[1] + vehicles_df.shape[1]

57

# Renaming Column

In [9]:
# characteristic 
charac_columns = {"an":"year",
                  "mois":"month",
                  "jour":"day",
                  "hrmn":"time",
                  "lum":"lighting",
                  "agg":"agg??",
                  "int":"intersection",
                  "atm":"atmosphere",
                  "col":"collision",
                  "com":"municipality",
                  "adr":"postal_address",
                  "gps":"GPS",
                  "lat":"latitude",
                  "long":"longitude",
                  "dep":"department"}

charac_df.rename(columns=charac_columns, inplace=True)

In [10]:
# users
users_columns = {"place":"place??",
                 "catu":"user_category",
                 "grav":"accident_severity",
                 "sexe":"user_sex",
                 "trajet":"trajet??",
                 "secu":"safety_equipt",
                 "locp":"pedestrian_loc",
                 "actp":"pedestrian_action",
                 "etatp":"pedestrian_company",
                 "an_nais":"an_nais??",
                 "num_veh":"vehicle_ID"}

users_df.rename(columns=users_columns, inplace=True)

In [11]:
# places 
places_columns = {"catr":"road_category",
                  "voie":"road_number",
                  "v1":"index_route_number",
                  "v2":"index_road",
                  "circ":"traff_regime",
                  "nbv":"no_traff_lanes",
                  "vosp":"reserved_lane",
                  "prof":"longitud_profile",
                  "pr":"home_PR_number",
                  "pr1":"distance_to_PR",
                  "plan":"drawing_plan",
                  "lartpc":"solid_land",
                  "larrout":"road_width",
                  "surf":"surface_cond",
                  "infra":"infrastructure",
                  "situ":"acc_situation",
                  "env1":"school_point"}

places_df.rename(columns=places_columns, inplace=True)

In [12]:
charac_df.head()

,Num_Acc,year,month,day,time,lighting,agg??,intersection,atmosphere,collision,municipality,postal_address,GPS,latitude,longitude,department
0,201600000001,16,2,1,1445,1,2,1,8.0,3.0,5.0,"46, rue Sonneville",M,0.0,0.0,590
1,201600000002,16,3,16,1800,1,2,6,1.0,6.0,5.0,1a rue du cimeti√®re,M,0.0,0.0,590
2,201600000003,16,7,13,1900,1,1,1,1.0,6.0,11.0,NaN,M,0.0,0.0,590
3,201600000004,16,8,15,1930,2,2,1,7.0,3.0,477.0,52 rue victor hugo,M,0.0,0.0,590
4,201600000005,16,12,23,1100,1,2,3,1.0,3.0,11.0,rue Joliot curie,M,0.0,0.0,590

In [13]:
users_df.head()

,Num_Acc,place??,user_category,accident_severity,user_sex,trajet??,safety_equipt,pedestrian_loc,pedestrian_action,pedestrian_company,an_nais??,vehicle_ID
0,201600000001,1.0,1,1,2,0.0,11.0,0.0,0.0,0.0,1983.0,B02
1,201600000001,1.0,1,3,1,9.0,21.0,0.0,0.0,0.0,2001.0,A01
2,201600000002,1.0,1,3,1,5.0,11.0,0.0,0.0,0.0,1960.0,A01
3,201600000002,2.0,2,3,1,0.0,11.0,0.0,0.0,0.0,2000.0,A01
4,201600000002,3.0,2,3,2,0.0,11.0,0.0,0.0,0.0,1962.0,A01

In [14]:
places_df.head()

,Num_Acc,road_category,road_number,index_route_number,index_road,traff_regime,no_traff_lanes,home_PR_number,distance_to_PR,reserved_lane,longitud_profile,drawing_plan,solid_land,road_width,surface_cond,infrastructure,acc_situation,school_point
0,201600000001,3.0,39,NaN,NaN,2.0,0.0,NaN,NaN,0.0,1.0,3.0,0.0,0.0,1.0,0.0,1.0,0.0
1,201600000002,3.0,39,NaN,NaN,1.0,0.0,NaN,NaN,0.0,1.0,2.0,0.0,58.0,1.0,0.0,1.0,0.0
2,201600000003,3.0,1,NaN,NaN,2.0,2.0,NaN,NaN,0.0,1.0,3.0,0.0,68.0,2.0,0.0,3.0,99.0
3,201600000004,4.0,0,NaN,NaN,2.0,0.0,NaN,NaN,0.0,1.0,1.0,0.0,0.0,1.0,0.0,1.0,99.0
4,201600000005,4.0,0,NaN,NaN,0.0,0.0,NaN,NaN,0.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0,3.0

# Dropping Column

some columns can be dropped straight away as they do not contain enough information

In [15]:
#columns to drop
charac_df.drop(columns = ['agg??', 'municipality', 'department'], inplace = True)
users_df.drop(columns = ["place??", "trajet??", "an_nais??", "safety_equipt"], inplace = True)
places_df.drop(columns = ["road_number", "index_route_number", "index_road", "home_PR_number",
                        "distance_to_PR", "solid_land", "road_width", "school_point"], inplace=True)

In [16]:
charac_df.head()

,Num_Acc,year,month,day,time,lighting,intersection,atmosphere,collision,postal_address,GPS,latitude,longitude
0,201600000001,16,2,1,1445,1,1,8.0,3.0,"46, rue Sonneville",M,0.0,0.0
1,201600000002,16,3,16,1800,1,6,1.0,6.0,1a rue du cimeti√®re,M,0.0,0.0
2,201600000003,16,7,13,1900,1,1,1.0,6.0,NaN,M,0.0,0.0
3,201600000004,16,8,15,1930,2,1,7.0,3.0,52 rue victor hugo,M,0.0,0.0
4,201600000005,16,12,23,1100,1,3,1.0,3.0,rue Joliot curie,M,0.0,0.0

In [17]:
users_df.head()

,Num_Acc,user_category,accident_severity,user_sex,pedestrian_loc,pedestrian_action,pedestrian_company,vehicle_ID
0,201600000001,1,1,2,0.0,0.0,0.0,B02
1,201600000001,1,3,1,0.0,0.0,0.0,A01
2,201600000002,1,3,1,0.0,0.0,0.0,A01
3,201600000002,2,3,1,0.0,0.0,0.0,A01
4,201600000002,2,3,2,0.0,0.0,0.0,A01

In [18]:
places_df.head()

,Num_Acc,road_category,traff_regime,no_traff_lanes,reserved_lane,longitud_profile,drawing_plan,surface_cond,infrastructure,acc_situation
0,201600000001,3.0,2.0,0.0,0.0,1.0,3.0,1.0,0.0,1.0
1,201600000002,3.0,1.0,0.0,0.0,1.0,2.0,1.0,0.0,1.0
2,201600000003,3.0,2.0,2.0,0.0,1.0,3.0,2.0,0.0,3.0
3,201600000004,4.0,2.0,0.0,0.0,1.0,1.0,1.0,0.0,1.0
4,201600000005,4.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,1.0

In [19]:
# characteristics

#creating a new column localization using postal address
charac_df['localization'] = charac_df.postal_address.isnull()

In [20]:
charac_df.head()

,Num_Acc,year,month,day,time,lighting,intersection,atmosphere,collision,postal_address,GPS,latitude,longitude,localization
0,201600000001,16,2,1,1445,1,1,8.0,3.0,"46, rue Sonneville",M,0.0,0.0,False
1,201600000002,16,3,16,1800,1,6,1.0,6.0,1a rue du cimeti√®re,M,0.0,0.0,False
2,201600000003,16,7,13,1900,1,1,1.0,6.0,NaN,M,0.0,0.0,True
3,201600000004,16,8,15,1930,2,1,7.0,3.0,52 rue victor hugo,M,0.0,0.0,False
4,201600000005,16,12,23,1100,1,3,1.0,3.0,rue Joliot curie,M,0.0,0.0,False

In [21]:
dfm = pd.merge(charac_df, users_df, on = 'Num_Acc', how = 'left')

In [22]:
dfm = pd.merge(dfm, places_df, on = 'Num_Acc', how='left')
dfm.head()

,Num_Acc,year,month,day,time,lighting,intersection,atmosphere,collision,postal_address,...,vehicle_ID,road_category,traff_regime,no_traff_lanes,reserved_lane,longitud_profile,drawing_plan,surface_cond,infrastructure,acc_situation
0,201600000001,16,2,1,1445,1,1,8.0,3.0,"46, rue Sonneville",...,B02,3.0,2.0,0.0,0.0,1.0,3.0,1.0,0.0,1.0
1,201600000001,16,2,1,1445,1,1,8.0,3.0,"46, rue Sonneville",...,A01,3.0,2.0,0.0,0.0,1.0,3.0,1.0,0.0,1.0
2,201600000002,16,3,16,1800,1,6,1.0,6.0,1a rue du cimeti√®re,...,A01,3.0,1.0,0.0,0.0,1.0,2.0,1.0,0.0,1.0
3,201600000002,16,3,16,1800,1,6,1.0,6.0,1a rue du cimeti√®re,...,A01,3.0,1.0,0.0,0.0,1.0,2.0,1.0,0.0,1.0
4,201600000002,16,3,16,1800,1,6,1.0,6.0,1a rue du cimeti√®re,...,A01,3.0,1.0,0.0,0.0,1.0,2.0,1.0,0.0,1.0

In [23]:
print(dfm.shape)
print(charac_df.shape)
print(users_df.shape)
print(places_df.shape)

(1876005, 30)
(839985, 14)
(1876005, 8)
(839985, 10)

#  Mapping of features values

To make the datasets and plots easier to understand, the values of each columns are mapped to their corresponding meaning

***CARACTERISTICS :***

Num_Acc : Accident ID

jour : Day of the accident

mois : Month of the accident

an : Year of the accident

hrmn : Time of the accident in hour and minutes (hhmm)

lum : Lighting : lighting conditions in which the accident occurred

1 - Full day

2 - Twilight or dawn

3 - Night without public lighting

4 - Night with public lighting not lit

5 - Night with public lighting on

dep : Departmeent : INSEE Code (National Institute of Statistics and Economic Studies) of the departmeent followed
by a 0 (201 Corse-du-Sud - 202 Haute-Corse)

com : Municipality: The commune number is a code given by INSEE. The code has 3 numbers set to the right.

Localisation :

1 - Out of agglomeration

2 - In built-up areas

int : Type of Intersection :

1 - Out of intersection

2 - Intersection in X

3 - Intersection in T

4 - Intersection in Y

5 - Intersection with more than 4 branches

6 - Giratory

7 - Place

8 - Level crossing

9 - Other intersection

atm : Atmospheric conditions:

1 - Normal

2 - Light rain

3 - Heavy rain

4 - Snow - hail

5 - Fog - smoke

6 - Strong wind - storm

7 - Dazzling weather

8 - Cloudy weather

9 - Other

col : Type of collision:

1 - Two vehicles - frontal

2 - Two vehicles - from the rear

3 - Two vehicles - by the side

4 - Three vehicles and more - in chain

5 - Three or more vehicles - multiple collisions

6 - Other collision

7 - Without collision

adr : Postal address: variable filled in for accidents occurring in built-up areas

gps : GPS coding: 1 originator character:

M = M√©tropole

A = Antilles (Martinique or Guadeloupe)

G = Guyane

R = R√©union

Y = Mayotte

Geographic coordinates in decimal degrees:

lat : Latitude

long : Longitude

In [ ]:
charac_df.columns

In [ ]:
# characteristics

#creating a new column localization using postal address
#charac_df['localization'] = charac_df.postal_address.isnull()

In [ ]:
charac_df['intersection'].unique()

In [ ]:
localization_map = {True : "Out of agglomeration", 
                    False : "In built-up areas"}


lighting_map = {1 : 'Full day', 
               2 : 'Twilight or dawn', 
               3 : 'Night without public lighting', 
               4 : 'Night with public lighting not lit',
               5 : 'Night with public lighting on'}


intersection_map = {0 : 'not specified or not applicable',
                    1 : 'Out of intersection',
                    2 : 'Intersection in X',
                    3 : 'Intersection in T',
                    4 : 'Intersection in Y',
                    5 : 'Intersection with more than 4 branches',
                    6 : 'Giratory',
                    7 : 'Place',
                    8 : 'Level crossing',
                    9 : 'Other intersection'}


atmosphere_map = {1 : 'Normal',
                  2 : 'Light rain',
                  3 : 'Heavy rain',
                  4 : 'Snow - hail',
                  5 : 'Fog - smoke',
                  6 : 'Strong wind - storm',
                  7 : 'Dazzling weather',
                  8 : 'Cloudy weather',
                  9 : 'Other'}


collision_map = {1 : 'Two vehicles - frontal',
                 2 : 'Two vehicles - from the rear',
                 3 : 'Two vehicles - by the side',
                 4 : 'Three vehicles and more - in chain',
                 5 : 'Three or more vehicles - multiple collisions',
                 6 : 'Other collision',
                 7 : 'Without collision'}


gps_map = {'M' : 'M√©tropole', 'A' : 'Antilles (Martinique or Guadeloupe)', 'G' : 'Guyane', 'R' : 'R√©union', 'Y' : 'Mayotte'}

In [ ]:
charac_df['localization'] = charac_df.localization.map(localization_map)

charac_df['lighting'] = charac_df.lighting.map(lighting_map)

charac_df['intersection'] = charac_df.intersection.map(intersection_map)

charac_df['atmosphere'] = charac_df.atmosphere.map(atmosphere_map)

charac_df['collision'] = charac_df.collision.map(collision_map)

charac_df['GPS'] = charac_df.GPS.map(gps_map)

***USERS:***

Acc_number: Accident identifier.

Num_Veh: Identification of the vehicle taken back for each user occupying this vehicle (including pedestrians who are
attached to the vehicles that hit them)

place: Allows to locate the place occupied in the vehicle by the user at the time of the accident

catu: User category:

1 - Driver

2 - Passenger

3 - Pedestrian

4 - Pedestrian in rollerblade or scooter

grav: Severity of the accident: The injured users are classified into three categories of victims plus the uninjured

1 - Unscathed

2 - Killed

3 - Hospitalized wounded

4 - Light injury

sex: Sex of the user

1 - Male

2 - Female

Year_on: Year of birth of the user

trip: Reason for traveling at the time of the accident:

1 - Home - work

2 - Home - school

3 - Shopping - Shopping

4 - Professional use

5 - Promenade - leisure

9 - Other

secu: on 2 characters:
the first concerns the existence of a safety equipment

1 - Belt

2 - Helmet

3 - Children's device

4 - Reflective equipment

9 - Other

the second is the use of Safety Equipment

1 - Yes

2 - No

3 - Not determinable

locp: Location of the pedestrian:

On pavement:

1 - A + 50 m from the pedestrian crossing

2 - A - 50 m from the pedestrian crossing

On pedestrian crossing:

3 - Without light signaling

4 - With light signaling

Various:

5 - On the sidewalk

6 - On the verge

7 - On refuge or BAU

8 - On against aisle

actp: Action of the pedestrian:

Moving

0 - not specified or not applicable

1 - Meaning bumping vehicle

2 - Opposite direction of the vehicle
Various

3 - Crossing

4 - Masked

5 - Playing - running

6 - With animal

9 - Other

etatp: This variable is used to specify whether the injured pedestrian was alone or not

1 - Only

2 - Accompanied

3 - In a group

In [ ]:
users_df.columns

In [ ]:
users_df['pedestrian_company'].unique()

In [ ]:
# users data 
user_category_map = {1 : 'Driver',
                     2 : 'Passenger',
                     3 : 'Pedestrian',
                     4 : 'Pedestrian in rollerblade or scooter'}

accident_severity_map = {1 : 'Unscathed',
                         2 : 'Killed',
                         3 : 'Hospitalized wounded',
                         4 : 'Light injury'}

user_sex_map = {1 : 'Male', 2: 'Female'}

pedestrian_loc_map = {0.0 : 'not specified or not applicable',
                      1.0 : 'pavement crossing(A + 50 )',
                      2.0 : 'pavement crossing(A - 50 )',
                      3.0 : 'crossing no signaling',
                      4.0 : 'crossing light signaling',
                      5.0 : 'On the sidewalk',
                      6.0 : 'On the verge',
                      7.0 : 'On refuge or BAU',
                      8.0 : 'On against aisle'}

pedestrian_action_map = {0.0 : 'not specified or not applicable',
                         1.0 : 'Meaning bumping vehicle',
                         2.0 : 'Opposite direction of the vehicle Various',
                         3.0 : 'Crossing',
                         4.0 : 'Masked',
                         5.0 : 'Playing - running',
                         6.0 : 'With animal',
                         9.0 : 'Other'}

pedestrian_company_map = {0.0: 'not specified or not applicable',
                          1.0 : 'Only',
                          2.0 : 'Accompanied',
                          3.0 : 'In a group'}



users_df['user_category'] = users_df['user_category'].map(user_category_map)
users_df['accident_severity'] = users_df['accident_severity'].map(accident_severity_map)
users_df['user_sex'] = users_df['user_sex'].map(user_sex_map)
users_df['pedestrian_loc'] = users_df['pedestrian_loc'].map(pedestrian_loc_map)
users_df['pedestrian_action'] = users_df['pedestrian_action'].map(pedestrian_action_map)
users_df['pedestrian_company'] = users_df['pedestrian_company'].map(pedestrian_company_map)

***places data***

Num_Acc : Accident ID

catr : Category of road:

1 - Highway

2 - National Road

3 - Departmental Road

4 - Communal Way

5 - Off public network

6 - Parking lot open to public traffic

9 - other

voie : Road Number

V1: Numeric index of the route number (example: 2 bis, 3 ter etc.)

V2: Letter alphanumeric index of the road

circ: Traffic regime:

1 - One way

2 - Bidirectional

3 - Separated carriageways

4 - With variable assignment channels

nbv: Total number of traffic lanes

vosp: Indicates the existence of a reserved lane, regardless of whether or not the accident occurs on that lane.

1 - Bike path

2 - Cycle Bank

3 - Reserved channel

Prof: Longitudinal profile describes the gradient of the road at the accident site

1 - Dish

2 - Slope

3 - Hilltop

4- Hill bottom

pr: Home PR number (upstream terminal number)

pr1: Distance in meters to the PR (relative to the upstream terminal)

plan: Drawing in plan:

1 - Straight part

2 - Curved on the left

3 - Curved right

4 - In "S"

lartpc: Central solid land width (TPC) if there is

larrout: Width of the roadway assigned to vehicle traffic are not included the emergency stop strips,
CPRs and parking spaces

surf: surface condition

1 - normal

2 - wet

3 - puddles

4 - flooded

5 - snow

6 - mud

7 - icy

8 - fat - oil

9 - other

infra: Development - Infrastructure:

1 - Underground - tunnel

2 - Bridge - autopont

3 - Exchanger or connection brace

4 - Railway

5 - Carrefour arranged

6 - Pedestrian area

7 - Toll zone

situ: Situation of the accident:

1 - On the road

2 - On emergency stop band

3 - On the verge

4 - On the sidewalk

5 - On bike path

env1: school point: near a school

In [ ]:
places_df.columns

In [ ]:
places_df['acc_situation'].unique()

In [ ]:
road_category_map = {1.0 : 'Highway', 2.0 : 'National Road',  3.0 : 'Departmental Road', 4.0 : 'Communal Way',
                     5.0 : 'Off public network', 6.0 : 'Parking lot open to public traffic',9.0 : 'other'}

traffic_regime_map = {0.0: 'not applicable', 1.0 : 'One way', 2.0 : 'Bidirectional', 3.0 : 'Separated carriageways', 4.0 : 'With variable assignment channels'}

reserved_lane_map = {0.0: 'not applicable', 1.0 : 'Bike path', 2.0 : 'Cycle Bank', 3.0 : 'Reserved channel'}

longitude_profile_map = {0.0: 'not applicable', 1.0 : 'Dish', 2.0 : 'Slope', 3.0 : 'Hilltop', 4.0 : 'Hill bottom'}

drawing_plan_map = {0.0: 'not applicable',1.0 : 'Straight part', 2.0 : 'Curved on the left', 3.0 : 'Curved right', 4.0 : 'In S'}

surface_cond_map = {0.0: 'not applicable', 1.0 : 'normal', 2.0 : 'wet', 3.0 : 'puddles', 4.0 : 'flooded', 5.0 : 'snow', 6.0 : 'mud', 7.0 : 'icy', 8.0 : 'fat - oil', 9.0 : 'other'}

infrastructure_map = {0.0: 'not applicable', 1.0 : 'Underground - tunnel', 2.0 : 'Bridge - autopont', 3.0 : 'Exchanger or connection brace', 4.0 : 'Railway', 
                      5.0 : 'Carrefour arranged', 6.0 : 'Pedestrian area', 7.0 : 'Toll zone'}

acc_situation_map = {0.0: 'not applicable', 1.0 : 'On the road', 2.0 : 'On emergency stop band', 3.0 : 'On the verge', 4.0 : 'On the sidewalk', 5.0 : 'On bike path'}

places_df['road_category'] = places_df['road_category'].map(road_category_map)
places_df['traff_regime'] = places_df['traff_regime'].map(traffic_regime_map)
places_df['reserved_lane'] = places_df['reserved_lane'].map(reserved_lane_map)
places_df['longitud_profile'] = places_df['longitud_profile'].map(longitude_profile_map)
places_df['drawing_plan'] = places_df['drawing_plan'].map(drawing_plan_map)
places_df['surface_cond'] = places_df['surface_cond'].map(surface_cond_map)
places_df['infrastructure'] = places_df['infrastructure'].map(infrastructure_map)
places_df['acc_situation'] = places_df['acc_situation'].map(acc_situation_map)

***VEHICLES:***

Num_Acc
Accident ID

Num_Veh
Identification of the vehicle taken back for each user occupying this vehicle (including pedestrians who are
attached to vehicles that hit them) - alphanumeric code

GP
Flow direction :

1 - PK or PR or increasing postal address number

2 - PK or PR or descending postal address number

CATV
Category of vehicle:

01 - Bicycle

02 - Moped <50cm3

03 - Cart (Quadricycle with bodied motor) (formerly "cart or motor tricycle")

04 - Not used since 2006 (registered scooter)

05 - Not used since 2006 (motorcycle)

06 - Not used since 2006 (side-car)

07 - VL only

08 - Not used category (VL + caravan)

09 - Not used category (VL + trailer)

10 - VU only 1,5T <= GVW <= 3,5T with or without trailer (formerly VU only 1,5T <= GVW <= 3,5T)

11 - Most used since 2006 (VU (10) + caravan)

12 - Most used since 2006 (VU (10) + trailer)

13 - PL only 3,5T

# Merging Datasets

all four datasets can be merged on Num_Acc(accident id) column

In [ ]:
charac_df.head()

In [ ]:
holidays_df.head()

In [ ]:
places_df.head()

In [ ]:
users_df.head()

In [ ]:
vehicles_df.head()

In [ ]:
df = pd.merge(charac_df, users_df, on = 'Num_Acc', how = 'left')

In [ ]:
df.head()

In [ ]:
print(f'shape of merged_df {df.shape}')
print(f'shape of merged_df {charac_df.shape}')
print(f'shape of merged_df {users_df.shape}')

In [ ]:
df = pd.merge(df, places_df, on = 'Num_Acc', how='left')
df.head()

In [ ]:
print(f'shape of merged_df {df.shape}')
print(f'shape of merged_df {places_df.shape}')

# Feature Engineering on merged dataset

In [ ]:
df.info()

# Handling Date and Time

In [ ]:
day_month_year = df['day'].astype(str) + '/' + df['month'].astype(str) + '/' + df['year'].astype(str)

In [ ]:
day_month_year[:5]

In [ ]:
df['date'] = pd.to_datetime(day_month_year)

df.drop(columns = ['day', 'month', 'year'], inplace = True)

df.insert(1, 'date', df.pop('date'))

In [ ]:
df.head()

In [ ]:
df['time'] = df.time.astype(str)

In [ ]:
df['hours'] = df['time'].apply(lambda x: x[:-2])
df['minute'] = df['time'].apply(lambda x: x[-2:])

df.drop(columns = ['time'], inplace = True)

df.insert(2, "hours", df.pop('hours'))
df.insert(3, 'minute', df.pop('minute'))

In [ ]:
df.head()

In [ ]:
df[df['hours'] == ""].shape

In [ ]:
df[df['hours'] == ""].head()

In [ ]:
df['hours'].replace(to_replace = "", value = '0', inplace = True)

In [ ]:
df[df['hours'] == ""].shape

In [ ]:
df.info()

In [ ]:
df.head()

In [ ]:
dfm.drop(columns = ['day', 'month', 'year','time'], inplace = True)

In [ ]:
dfm.insert(1, "date", df['date'])
dfm.insert(2, "hours", df['hours'])
dfm.insert(3, 'minute', df['minute'])

In [ ]:
dfm.head()

In [ ]:
dfm.info()

### Handling Missing Values

In [ ]:
def missing_vals(df):
    for column in df.columns :
        null_count = df.isnull()[column].sum()
        
        if null_count == 0:
            continue
        
        total_count = df[column].shape[0]
        percentage = round((null_count/total_count)*100, 2)
        
        print(f'percentage of missing vals in {column} : {percentage}')

In [ ]:
missing_vals(df)

In [ ]:
missing_vals(dfm)

In [ ]:
plt.figure(figsize = (10,5))
sns.heatmap(df.isnull(),yticklabels = False, cbar =  True)
plt.show()

In [ ]:
#drop columns having missing vals greater than 50 percent
df.drop(columns = ['GPS','latitude','longitude'], inplace = True)

In [ ]:
dfm.drop(columns = ['GPS','latitude','longitude'], inplace = True)

In [ ]:
df.columns

In [ ]:
dfm.columns

In [ ]:
#replace the missing vals by mode in the columns having missing vals less than 50 percent
df['atmosphere'].fillna(value = df['atmosphere'].mode()[0], inplace = True)
df['collision'].fillna(value = df['collision'].mode()[0], inplace = True)
df['pedestrian_loc'].fillna(value = df['pedestrian_loc'].mode()[0], inplace = True)
df['pedestrian_action'].fillna(value = df['pedestrian_action'].mode()[0], inplace = True)
df['pedestrian_company'].fillna(value = df['pedestrian_company'].mode()[0], inplace = True)
df['road_category'].fillna(value = df['road_category'].mode()[0], inplace = True)
df['traff_regime'].fillna(value = df['traff_regime'].mode()[0], inplace = True)
df['no_traff_lanes'].fillna(value = df['no_traff_lanes'].mode()[0], inplace = True)
df['reserved_lane'].fillna(value = df['reserved_lane'].mode()[0], inplace = True)
df['longitud_profile'].fillna(value = df['longitud_profile'].mode()[0], inplace = True)
df['drawing_plan'].fillna(value = df['drawing_plan'].mode()[0], inplace = True)
df['surface_cond'].fillna(value = df['surface_cond'].mode()[0], inplace = True)
df['infrastructure'].fillna(value = df['infrastructure'].mode()[0], inplace = True)
df['acc_situation'].fillna(value = df['acc_situation'].mode()[0], inplace = True)



#postal address can be left blank
df['postal_address'].fillna(value = 'None', inplace = True)

In [ ]:
missing_vals(df)

In [ ]:
df.acc_situation.unique()

In [ ]:
df.head()

In [ ]:
dfm['atmosphere'].fillna(value = dfm['atmosphere'].mode()[0], inplace = True)
dfm['collision'].fillna(value = dfm['collision'].mode()[0], inplace = True)
dfm['pedestrian_loc'].fillna(value = dfm['pedestrian_loc'].mode()[0], inplace = True)
dfm['pedestrian_action'].fillna(value = dfm['pedestrian_action'].mode()[0], inplace = True)
dfm['pedestrian_company'].fillna(value = dfm['pedestrian_company'].mode()[0], inplace = True)
dfm['road_category'].fillna(value = dfm['road_category'].mode()[0], inplace = True)
dfm['traff_regime'].fillna(value = dfm['traff_regime'].mode()[0], inplace = True)
dfm['no_traff_lanes'].fillna(value = dfm['no_traff_lanes'].mode()[0], inplace = True)
dfm['reserved_lane'].fillna(value = dfm['reserved_lane'].mode()[0], inplace = True)
dfm['longitud_profile'].fillna(value = dfm['longitud_profile'].mode()[0], inplace = True)
dfm['drawing_plan'].fillna(value = dfm['drawing_plan'].mode()[0], inplace = True)
dfm['surface_cond'].fillna(value = dfm['surface_cond'].mode()[0], inplace = True)
dfm['infrastructure'].fillna(value = dfm['infrastructure'].mode()[0], inplace = True)
dfm['acc_situation'].fillna(value = dfm['acc_situation'].mode()[0], inplace = True)



#postal address can be left blank
dfm['postal_address'].fillna(value = 'None', inplace = True)

In [ ]:
dfm.head()

# Handling Duplicates

The users' dataset can have multiple entries that corresponds to the same accident ID, simply because more than one person can be involved in the same accident. Thus when a merge was performed on the accident ID, other datasets would 'duplicate' their entries to fill up the users' dataset entries. Our project aims to predicting the most severe injury that could occur in due to an accident, therefore we can remove all 'duplicates' for the same accident ID, leaving behind on the most severe injury condition.

In [ ]:
df['accident_severity'].unique()

In [ ]:
# 1 - Unscathed

# 2 - Killed

# 3 - Hospitalized wounded

# 4 - Light injury 

dfm['accident_severity'].unique()

In [ ]:
# remap for sorting 
severity_map = {'Unscathed' : 1, 'Killed' : 2, 'Hospitalized wounded' : 3, 'Light injury' : 4}
df['accident_severity'] = df['accident_severity'].map(severity_map)

In [ ]:
df.columns

In [ ]:
df.sort_values(by='accident_severity', ascending = False, inplace = True)
df.head(10)[['Num_Acc', 'atmosphere', 'accident_severity']]

In [ ]:
df["accident_severity"].value_counts()

In [ ]:
df.drop_duplicates('Num_Acc', inplace = True)

In [ ]:
df["accident_severity"].value_counts()

1    382951
4    261174
3    169974
2     25886

In [ ]:
dfm.sort_values(by='accident_severity', ascending = False, inplace = True)
dfm.head(10)[['Num_Acc', 'atmosphere', 'accident_severity']]

In [ ]:
dfm["accident_severity"].value_counts()

In [ ]:
dfm.drop_duplicates('Num_Acc', inplace = True)

In [ ]:
dfm["accident_severity"].value_counts()

all column contaning Unscathed class were lost

In [ ]:
# reorder the dataset back
df.sort_index(axis = 0, ascending = True, inplace = True)
df.reset_index(drop=True, inplace = True)

In [ ]:
accident_severity_map = {1:'Unscathed', 2:'Killed', 3:'Hospitalized wounded', 4:'Light injury'}
df['accident_severity'] = df['accident_severity'].map(accident_severity_map)

In [ ]:
df.head(10)[['Num_Acc', 'atmosphere', 'accident_severity']]

# Data Visualization

In [ ]:
df.info()

In [ ]:
sns.set_style('whitegrid')
acc = df['accident_severity']

In [ ]:
acc

# Date and Time variation

In [ ]:
fig, axes = plt.subplots(2,2)
fig.set_size_inches(16,8)

sns.countplot(x=df["date"].dt.year, palette='winter',ax=axes[0,0]).set(xlabel="year") 
sns.countplot(x=df["date"].dt.month, palette ='winter',ax=axes[0,1]).set(xlabel="month")
sns.countplot(x=df["date"].dt.weekday, palette="winter", ax=axes[1,0]).set(xlabel="weeday")
sns.countplot(x=df["hours"],palette='hot', ax=axes[1,1]).set(xlabel='hour')

plt.show()

* ### There is a yearly decrease in accident count
* ### The month and weekday do not show signoficant change in accident count
* ### The hourly accident count has a large variation, it is no doubt that more or less accidents occur at different times of the day

## Time based variation on accident severity

In [ ]:
fig, axes = plt.subplots(2,2)
fig.set_size_inches(16,8)

sns.countplot(x=df['date'].dt.year, hue=acc, palette="magma_r", ax=axes[0,0]).set(xlabel='Year')
sns.countplot(x=df['date'].dt.month, hue=acc, palette="magma_r", ax=axes[0,1]).set(xlabel='month')
sns.countplot(x=df['date'].dt.weekday, hue=acc, palette="magma_r", ax=axes[1,0]).set(xlabel='weekday')
sns.countplot(x=df['hours'], hue=acc, palette='winter', ax=axes[1,1]).set(xlabel='hours')

plt.show()

### The distribution of accident severity remains almost constant accross different time interval, except in the hourly variation. Hence none of the date & time variables except hour would be beneficial in predicting accident severity.

# Categorical variations

## All features of this dataset are categorical, the only logical analysis that can be done are based on occurance distribution (count)

In [ ]:
def compare_plots(column, palette="Twilight"):
    fig, axes = plt.subplots(1,2)
    fig.set_size_inches(16,5)
    
    sns.countplot(x=column, order=column.value_counts().index, ec='Black', palette=palette, ax=axes[0])
    sns.countplot(x=column, order=column.value_counts().index, hue=acc, ec='Blue', palette=palette, ax=axes[1])
    fig.autofmt_xdate(rotation=20)
    plt.show()

### Accident Severity

In [ ]:
plt.figure(figsize=(12,4))
sns.countplot(x=df['accident_severity'], order=df['accident_severity'].value_counts().index, ec='Black', palette ='ocean_r' )

plt.show()

### Lighting

In [ ]:
compare_plots(df['lighting'], 'Greens')

### Intersection

In [ ]:
compare_plots(df['intersection'], 'Oranges')

#### mostly accidents happened out of intersection

### Atmosphere

In [ ]:
compare_plots(df['atmosphere'], 'Blues')

### Collision

In [ ]:
compare_plots(df['collision'], 'RdPu')

#### Hospitalized injuriies are more than other injuries in case of frontal collisions

### Localisation

In [ ]:
compare_plots(df['localization'],'crest')

#### light injuries occurs more in build-up areas and in case of out of agglomeration, hospitalized injurries happened more in comparison to others

### User Category

In [ ]:
compare_plots(df['user_category'], "afmhot_r")

#### injuries occured more in case of drivers and chances of light injuries are more in all types of user category

### User Sex

In [ ]:
compare_plots(df['user_sex'], 'GnBu')

#### observation regaring user sex does not affect the severity of accidents, so this feature is not a direct predictor of the severity of accident and can dropped easily

### Pedestrian Action

In [ ]:
compare_plots(df['pedestrian_action'], 'flare')

#### pedestrian action are not specified in case of maximum injuries

### pedestrian localization

In [ ]:
compare_plots(df['pedestrian_loc'], 'gist_ncar_r')

### Road Category

In [ ]:
compare_plots(df['road_category'], 'RdGy_r')

#### Accidents happen more on communal ways and chances of light injuries are more on communal ways, chances of hospitalized injuries and death are more in case of departmental road

### Reserved Lane

In [ ]:
compare_plots(df['reserved_lane'], 'gist_ncar_r')

### Traffic Regime

In [ ]:
compare_plots(df['traff_regime'], 'BuGn')

#### probability of injuries are less where traffics have variable assignment channels and in case of bidirectional chances of all type of injuries are more in comparison to other regimes

### Number of traffic lanes

In [ ]:
df['no_traff_lanes'].value_counts()

#### a road of more than 50 traffic lanes appears to be unrealistic scenareo, This column contains a lot misinformation thus this column can be dropped

In [ ]:
df.drop(columns='no_traff_lanes', inplace = True)
dfm.drop(columns='no_traff_lanes', inplace = True)

### Longitudinal Profile

In [ ]:
compare_plots(df['longitud_profile'], 'OrRd')

#### Dish shape of longitudinal profile have more injuries than others types

### Drawing Plan

In [ ]:
compare_plots(df['drawing_plan'], 'Pastel2')

#### accidents occurs primarily in case of straight drawing plan and chances of all type of injuries are high in case of straught part drawing plan

### Surface Condition

In [ ]:
compare_plots(df['surface_cond'], 'Purples')

#### In most of the accidents, surface condtions are normal,

### Accident Situation

In [ ]:
compare_plots(df['acc_situation'], 'Accent')

#### As obvious accidents happens on roal in most of the cases

### Infrastructure

In [ ]:
compare_plots(df['infrastructure'], 'OrRd')

# Feature Importance

### Dropping Columns

In [ ]:
df.info()

#### Num_Acc, date, minute, postal_address, user_sex, vehicle_ID are the columns which do not make any inference to predict the severity of accident so we can drop these feature.

In [ ]:
df.drop(columns=['Num_Acc','date','minute','postal_address','user_sex','vehicle_ID'], inplace =True)
dfm.drop(columns=['Num_Acc','date','minute','postal_address','user_sex','vehicle_ID'], inplace =True)

In [ ]:
df.columns, len(df.columns)

In [ ]:
dfm.columns, len(dfm.columns)

### Feature Importance

##### Feature Importance refers to techniques that calculate a score for all the input features for a given model ‚Äî the scores simply represent the ‚Äúimportance‚Äù of each feature. A higher score means that the specific feature will have a larger effect on the model that is being used to predict a certain variable.

In [ ]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import OneHotEncoder, LabelEncoder, MinMaxScaler
from sklearn.metrics import classification_report

In [ ]:
def transformation(column):
  max_value = column.max()
  sin_values = [np.sin((2*22*int(x))/(int(max_value)*7)) for x in list(column)]
  cos_values = [np.cos((2*22*int(x))/(int(max_value)*7)) for x in list(column)]
  return sin_values, cos_values

In [ ]:
hours_sin, hours_cos = transformation(df.hours)

In [ ]:
df['hours_sin'] = hours_sin
df['hours_cos'] = hours_cos
df.drop(columns = 'hours', inplace = True)

In [ ]:
df.head()

In [ ]:
dfm.shape[1]

In [ ]:
dfm.insert(18, 'hours_sin', df['hours_sin'])
dfm.insert(19, 'hours_cos', df['hours_cos'])

In [ ]:
dfm.drop(columns='hours',inplace = True)

In [ ]:
dfm.head()

In [ ]:
dfm.hours_sin.isnull().sum()

In [ ]:
df.hours_sin.isnull().sum()

In [ ]:
# df.columns

In [ ]:
# column_for_le = 'localization'
# le = LabelEncoder()

# df[column_for_le] = le.fit_transform(df[column_for_le])

In [ ]:
# df.head()

In [ ]:
df['accident_severity'].unique()

In [ ]:
accident_severity_dict = {'Light injury':1, 'Hospitalized wounded':2, 'Killed':3}
df['accident_severity'] = df['accident_severity'].map(accident_severity_dict)

In [ ]:
# accident_severity_dict

In [ ]:
df.head()

In [ ]:
"""columns_for_ohe = ['lighting', 'intersection', 'atmosphere', 'collision',
                   'user_category', 'pedestrian_action','road_category', 
                   'traff_regime', 'longitud_profile', 'drawing_plan',
                   'surface_cond', 'acc_situation']"""

In [ ]:
# ohe = OneHotEncoder(categories='auto')
# dfc = pd.get_dummies(df, columns=columns_for_ohe,drop_first=True)

In [ ]:
len(dfc.columns)

In [ ]:
# dfc.head(50)

In [ ]:
## Correlation
plt.figure(figsize=(40,20))
correlation = dfc.corr()
sns.heatmap(abs(correlation), annot=True, cmap='coolwarm')

In [ ]:
correlation

In [ ]:
dfc.to_csv("modeling_data.csv", index=False)